on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for manual build"
        required: false
        default: "Manual testing"
        type: string
jobs:
  build-and-publish:
    runs-on: docker
    container:
      image: docker:cli
    steps:
      - name: Install Node
        run: apk add --no-cache nodejs
      - name: Checkout code
        uses: actions/checkout@v6.0.2
      - name: Setup buildx
        uses: docker/setup-buildx-action@v3.12.0
      - name: Login to registry
        uses: docker/login-action@v3.7.0
        with:
          registry: codeberg.org
          username: ${{ env.FORGEJO_ACTOR }}
          password: ${{ secrets.registry_token }}
      - name: Get metadata
        uses: docker/metadata-action@v5.10.0
        id: docker_meta
        with:
          images: "codeberg.org/${{ env.FORGEJO_REPOSITORY }}"
          flavor: |
            latest=true
          tags: |
            type=ref,event=tag
      - name: Build and push
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          file: "Dockerfile"
          platforms: "linux/amd64,linux/arm64"
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          build-args: |
            VERSION=${{ steps.docker_meta.outputs.version }}
          push: true
