on: [push]
jobs:
  build-and-publish:
    runs-on: codeberg-small-lazy
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Login to Codeberg Registry
        run: |
          echo "${{ secrets.registry_token }}" | podman login codeberg.org -u ${{ env.FORGEJO_ACTOR }} --password-stdin
      - name: Build and Push
        run: |
          IMAGE_NAME=$(echo "codeberg.org/${{ env.FORGEJO_REPOSITORY }}" | tr '[:upper:]' '[:lower:]')
          podman build -t "$IMAGE_NAME:latest" -t "$IMAGE_NAME:${{ env.FORGEJO_SHA }}" .
          podman push "$IMAGE_NAME:${{ env.FORGEJO_SHA }}"
          podman push "$IMAGE_NAME:latest"
