on: [push]
jobs:
  build-and-publish:
    runs-on: docker
    container:
      image: ghcr.io/catthehacker/ubuntu:act-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup buildx
        uses: docker/setup-buildx-action@v3.12.0
      - name: Login to registry
        uses: docker/login-action@v3.6.0
        with:
          registry: codeberg.org
          username: ${{ env.FORGEJO_ACTOR }}
          password: ${{ secrets.registry_token }}
      - name: Get metadata
        uses: docker/metadata-action@v5.10.0
        id: docker_meta
        with:
          images: "codeberg.org/${{ env.FORGEJO_REPOSITORY }}"
          flavor: |
            latest=false
          tags: "type=sha"
      - name: Build and push
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          file: "Dockerfile"
          platforms: "linux/amd64,linux/arm64"
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          build-args: |
            VERSION=${{ steps.docker_meta.outputs.version }}
          push: true
